//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerNote
    {
        public int CustomerNoteID { get; set; }
        public int CustomerID { get; set; }
        public string Body { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string CreatedByUser { get; set; }
    }
}
